**First save a copy of this notebook in your Google drive.** Read this notebook from top to bottom and fill in the code as you go. Work together with your partner and discuss with other students in the class. Try to resolve any errors on your own first, but don't get stuck; ask for help!

For many of these questions, there are several ways to do it in Pandas. You only need to choose one that works. But you might want to experiment with multiple ways of doing the same thing to get practice working with Pandas.

## Titanic Data

 The Titanic data set (https://raw.githubusercontent.com/kevindavisross/data301/main/data/titanic.csv) contains information about 2206 passengers and crew members that were aboard the RMS Titanic when it sank on April 15, 1912.

1\. Read in the Titanic data set. What seems to be the observational unit?

The observational unit is each individual passenger or crew member aboard the Titanic.

In [13]:
import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/kevindavisross/data301/main/data/titanic.csv")
print(df)

                                name  gender   age             class embarked  \
0                Abbing, Mr. Anthony    male  42.0               3rd        S
1          Abbott, Mr. Eugene Joseph    male  13.0               3rd        S
2        Abbott, Mr. Rossmore Edward    male  16.0               3rd        S
3     Abbott, Mrs. Rhoda Mary 'Rosa'  female  39.0               3rd        S
4        Abelseth, Miss. Karen Marie  female  16.0               3rd        S
...                              ...     ...   ...               ...      ...
2202                Wynn, Mr. Walter    male  41.0         deck crew        B
2203             Yearsley, Mr. Harry    male  40.0  victualling crew        S
2204        Young, Mr. Francis James    male  32.0  engineering crew        S
2205             Zanetti, Sig. Minio    male  20.0  restaurant staff        S
2206              Zarracchi, Sig. L.    male  26.0  restaurant staff        S

            country  ticketno   fare  survived  pclass              crew
0     United States    5547.0   7.11         0     3.0               NaN
1     United States    2673.0  20.05         0     3.0               NaN
2     United States    2673.0  20.05         0     3.0               NaN
3           England    2673.0  20.05         1     3.0               NaN
4            Norway  348125.0   7.13         1     3.0               NaN
...             ...       ...    ...       ...     ...               ...
2202        England       NaN    NaN         1     NaN         deck crew
2203        England       NaN    NaN         1     NaN  victualling crew
2204        England       NaN    NaN         0     NaN  engineering crew
2205        England       NaN    NaN         0     NaN  restaurant staff
2206        England       NaN    NaN         0     NaN  restaurant staff

[2207 rows x 11 columns]

In [29]:
df.columns

Index(['gender', 'age', 'class', 'embarked', 'country', 'ticketno', 'fare',
       'survived', 'pclass', 'crew'],
      dtype='object')

2\. What column seems to be an appropriate index for this data frame? Can you think of any problems with using this column as the index?

Name, if two people have the same name

3\. Regardless of your answer to the previous question, write code to make "name" the index of the data frame.

In [19]:
df = df.set_index("name")
print(df)

                                gender   age             class embarked  \
name
Abbing, Mr. Anthony               male  42.0               3rd        S
Abbott, Mr. Eugene Joseph         male  13.0               3rd        S
Abbott, Mr. Rossmore Edward       male  16.0               3rd        S
Abbott, Mrs. Rhoda Mary 'Rosa'  female  39.0               3rd        S
Abelseth, Miss. Karen Marie     female  16.0               3rd        S
...                                ...   ...               ...      ...
Wynn, Mr. Walter                  male  41.0         deck crew        B
Yearsley, Mr. Harry               male  40.0  victualling crew        S
Young, Mr. Francis James          male  32.0  engineering crew        S
Zanetti, Sig. Minio               male  20.0  restaurant staff        S
Zarracchi, Sig. L.                male  26.0  restaurant staff        S

                                      country  ticketno   fare  survived  \
name
Abbing, Mr. Anthony             United States    5547.0   7.11         0
Abbott, Mr. Eugene Joseph       United States    2673.0  20.05         0
Abbott, Mr. Rossmore Edward     United States    2673.0  20.05         0
Abbott, Mrs. Rhoda Mary 'Rosa'        England    2673.0  20.05         1
Abelseth, Miss. Karen Marie            Norway  348125.0   7.13         1
...                                       ...       ...    ...       ...
Wynn, Mr. Walter                      England       NaN    NaN         1
Yearsley, Mr. Harry                   England       NaN    NaN         1
Young, Mr. Francis James              England       NaN    NaN         0
Zanetti, Sig. Minio                   England       NaN    NaN         0
Zarracchi, Sig. L.                    England       NaN    NaN         0

                                pclass              crew
name
Abbing, Mr. Anthony                3.0               NaN
Abbott, Mr. Eugene Joseph          3.0               NaN
Abbott, Mr. Rossmore Edward        3.0               NaN
Abbott, Mrs. Rhoda Mary 'Rosa'     3.0               NaN
Abelseth, Miss. Karen Marie        3.0               NaN
...                                ...               ...
Wynn, Mr. Walter                   NaN         deck crew
Yearsley, Mr. Harry                NaN  victualling crew
Young, Mr. Francis James           NaN  engineering crew
Zanetti, Sig. Minio                NaN  restaurant staff
Zarracchi, Sig. L.                 NaN  restaurant staff

[2207 rows x 10 columns]

 4\. Write code that returns the observations for  "Kelly, Mr. James". What do you notice? (You can also try "Green, Mr. George"). Note: you might try this both with "name" as the index and with it not as the index.

In [24]:
df.loc["Kelly, Mr. James"]

,gender,age,class,embarked,country,ticketno,fare,survived,pclass,crew
name,,,,,,,,,,
"Kelly, Mr. James",male,19.0,3rd,S,Scotland,363592.0,8.0100,0,3.0,NaN
"Kelly, Mr. James",male,44.0,3rd,Q,Ireland,330911.0,7.1607,0,3.0,NaN
"Kelly, Mr. James",male,44.0,engineering crew,S,England,NaN,NaN,0,NaN,engineering crew

5\. Write code to extract a single `DataFrame` containing the observations three members of the Widener family:
  - Widener, Mr. George Dunton
  - Widener, Mr. Harry Elkins
  - Widener, Mrs. Eleanor

What became of them? Using a search engine, what else can you learn about them? (Note: you could just provide a list of these names. But you might also want to experiment with functions for working with strings, e.g., [`str.contains`](https://pandas.pydata.org/docs/reference/api/pandas.Series.str.contains.html) to find all instances of "Widener"; in this case, it might be helpful to have name as a regular column and not the index.)

In [27]:
df[df.index.str.contains("Widener")]

,gender,age,class,embarked,country,ticketno,fare,survived,pclass,crew
name,,,,,,,,,,
"Widener, Mr. George Dunton",male,50.0,1st,S,United States,113503.0,211.1,0,1.0,NaN
"Widener, Mr. Harry Elkins",male,27.0,1st,S,United States,113503.0,211.1,0,1.0,NaN
"Widener, Mrs. Eleanor",female,50.0,1st,S,United States,113503.0,211.1,1,1.0,NaN

6\. Look at a few rows in the full data set. Try to identify what each variable measures. Also, try to identify each variable as either quantitative, categorical, or other. (In general, there should be a code book with information about all the variables. But try to infer what you can from context.)



| Variable   | What it measures                               | Type                      |
| ---------- | ---------------------------------------------- | ------------------------- |
| `gender`   | Passenger/crew member's gender                 | categorical
| `age`      | Age in years                                   | Quantitative              
| `class`    | Passenger class or type of crew member         | categorical
| `embarked` | Port where the person boarded (`S`, `C`, etc.) | categorical
| `country`  | Person's country                               | categorical 
| `ticketno` | Ticket number                                  | categorical
| `fare`     | Price paid for the ticket                      | Quantitative              
| `survived` | Whether the person survived                    | categorical
| `pclass`   | Passenger class, such as 1, 2, or 3            | categorical
| `crew`     | Whether/person's crew classification           | categorical

In [32]:
df.dtypes
df.sample(5, random_state=1)

,gender,age,class,embarked,country,ticketno,fare,survived,pclass,crew
name,,,,,,,,,,
"Light, Mr. Christopher William",male,20.0,engineering crew,S,England,NaN,NaN,0,NaN,engineering crew
"Fellowes, Mr. Alfred James",male,29.0,victualling crew,B,England,NaN,NaN,0,NaN,victualling crew
"Vanderplancke, Mr. Julius",male,31.0,3rd,S,Belgium,345763.0,18.0000,0,3.0,NaN
"Francatelli, Miss. Laura Mabel",female,32.0,1st,C,England,17485.0,56.1807,1,1.0,NaN
"Carlsson, Mr. Frans Olof",male,33.0,1st,S,United States,695.0,5.0000,0,1.0,NaN

7\. The variable `pclass` measures the class for passengers. Why are some of the values in this column `NaN`? Should this variable be categorical or quantitative? What type does Pandas this it is?

NaN appears because crew members don’t have a passenger class.
pclass should be treated as categorical.
Pandas currently stores it as float64 because it contains numeric values plus missing values.

In [34]:
print(df["pclass"].dtypes)
print(df["pclass"].value_counts())

float64
pclass
3.0    709
1.0    324
2.0    284
Name: count, dtype: int64

8\. Write code to cast `pclass` to the correct type. Repeat for any other variables that do not have the correct type.

In [37]:
df["pclass"] = df["pclass"].astype("category")
df["survived"] = df["survived"].astype("category")
df["ticketno"] = df["ticketno"].astype("category")
df.dtypes

gender        object
age          float64
class         object
embarked      object
country       object
ticketno    category
fare         float64
survived    category
pclass      category
crew          object
dtype: object

## Transforming Categorical Variables

A categorical variable can be transformed by mapping its levels to new levels. For example, we may only be interested in whether a person on the titanic was a passenger or a crew member. The variable `class` is too detailed for these purposes. We can create a new variable, `type`, that is derived from the existing variable `class`. Observations with a `class` of "1st", "2nd", or "3rd" get a value of "passenger", while observations with a `class` of "deck crew", "engineering crew", or "deck crew" get a value of "crew".

In [38]:
df["type"] = df["class"].map({
    "1st": "passenger",
    "2nd": "passenger",
    "3rd": "passenger",
    "victualling crew": "crew",
    "engineering crew": "crew",
    "deck crew": "crew"
})

df

,gender,age,class,embarked,country,ticketno,fare,survived,pclass,crew,type
name,,,,,,,,,,,
"Abbing, Mr. Anthony",male,42.0,3rd,S,United States,5547.0,7.11,0,3.0,NaN,passenger
"Abbott, Mr. Eugene Joseph",male,13.0,3rd,S,United States,2673.0,20.05,0,3.0,NaN,passenger
"Abbott, Mr. Rossmore Edward",male,16.0,3rd,S,United States,2673.0,20.05,0,3.0,NaN,passenger
"Abbott, Mrs. Rhoda Mary 'Rosa'",female,39.0,3rd,S,England,2673.0,20.05,1,3.0,NaN,passenger
"Abelseth, Miss. Karen Marie",female,16.0,3rd,S,Norway,348125.0,7.13,1,3.0,NaN,passenger
...,...,...,...,...,...,...,...,...,...,...,...
"Wynn, Mr. Walter",male,41.0,deck crew,B,England,NaN,NaN,1,NaN,deck crew,crew
"Yearsley, Mr. Harry",male,40.0,victualling crew,S,England,NaN,NaN,1,NaN,victualling crew,crew
"Young, Mr. Francis James",male,32.0,engineering crew,S,England,NaN,NaN,0,NaN,engineering crew,crew
"Zanetti, Sig. Minio",male,20.0,restaurant staff,S,England,NaN,NaN,0,NaN,restaurant staff,NaN
"Zarracchi, Sig. L.",male,26.0,restaurant staff,S,England,NaN,NaN,0,NaN,restaurant staff,NaN

Upon closer inspection of this `DataFrame`, we see that we accidentally left out the level "restaurant staff" in the input to `.map()`. Any levels that are unspecified will be mapped to the missing value `NaN`.

This suggests a more concise way to define the new variable `type`. We can specify only the levels for passengers in the mapping and then fill in the missing values afterwards.

In [39]:
df["type"] = df["class"].map({
    "1st": "passenger",
    "2nd": "passenger",
    "3rd": "passenger"
})

# Replace all missing values by "crew"
df["type"].fillna("crew", inplace=True)

df

<positron-console-cell-39>:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.

,gender,age,class,embarked,country,ticketno,fare,survived,pclass,crew,type
name,,,,,,,,,,,
"Abbing, Mr. Anthony",male,42.0,3rd,S,United States,5547.0,7.11,0,3.0,NaN,passenger
"Abbott, Mr. Eugene Joseph",male,13.0,3rd,S,United States,2673.0,20.05,0,3.0,NaN,passenger
"Abbott, Mr. Rossmore Edward",male,16.0,3rd,S,United States,2673.0,20.05,0,3.0,NaN,passenger
"Abbott, Mrs. Rhoda Mary 'Rosa'",female,39.0,3rd,S,England,2673.0,20.05,1,3.0,NaN,passenger
"Abelseth, Miss. Karen Marie",female,16.0,3rd,S,Norway,348125.0,7.13,1,3.0,NaN,passenger
...,...,...,...,...,...,...,...,...,...,...,...
"Wynn, Mr. Walter",male,41.0,deck crew,B,England,NaN,NaN,1,NaN,deck crew,crew
"Yearsley, Mr. Harry",male,40.0,victualling crew,S,England,NaN,NaN,1,NaN,victualling crew,crew
"Young, Mr. Francis James",male,32.0,engineering crew,S,England,NaN,NaN,0,NaN,engineering crew,crew
"Zanetti, Sig. Minio",male,20.0,restaurant staff,S,England,NaN,NaN,0,NaN,restaurant staff,crew
"Zarracchi, Sig. L.",male,26.0,restaurant staff,S,England,NaN,NaN,0,NaN,restaurant staff,crew

For more complex mappings, the `.map()` method also accepts a function. So the above is equivalent to

In [40]:
def class_to_type(c):
  if c in ["1st", "2nd", "3rd"]:
    return "passenger"
  else:
    return "crew"

df["class"].map(class_to_type)

name
Abbing, Mr. Anthony               passenger
Abbott, Mr. Eugene Joseph         passenger
Abbott, Mr. Rossmore Edward       passenger
Abbott, Mrs. Rhoda Mary 'Rosa'    passenger
Abelseth, Miss. Karen Marie       passenger
                                    ...
Wynn, Mr. Walter                       crew
Yearsley, Mr. Harry                    crew
Young, Mr. Francis James               crew
Zanetti, Sig. Minio                    crew
Zarracchi, Sig. L.                     crew
Name: class, Length: 2207, dtype: object

## Converting Quantitative Variables to Categorical Variables

Sometimes it is necessary to categorize quantitative variables. We can use the `cut` function in `pandas` to categorize or bin a quantitative variable, by specifying the endpoints of the bins. We can also provide labels for the bins.

In [41]:
df["age_categories"] = pd.cut(x = df["age"],
                                      bins = [0, 18, 30, 45, 65, 130],
                                      labels = ["<18", "18-30", "30-45", "45-65", "65+"])

df

,gender,age,class,embarked,country,ticketno,fare,survived,pclass,crew,type,age_categories
name,,,,,,,,,,,,
"Abbing, Mr. Anthony",male,42.0,3rd,S,United States,5547.0,7.11,0,3.0,NaN,passenger,30-45
"Abbott, Mr. Eugene Joseph",male,13.0,3rd,S,United States,2673.0,20.05,0,3.0,NaN,passenger,<18
"Abbott, Mr. Rossmore Edward",male,16.0,3rd,S,United States,2673.0,20.05,0,3.0,NaN,passenger,<18
"Abbott, Mrs. Rhoda Mary 'Rosa'",female,39.0,3rd,S,England,2673.0,20.05,1,3.0,NaN,passenger,30-45
"Abelseth, Miss. Karen Marie",female,16.0,3rd,S,Norway,348125.0,7.13,1,3.0,NaN,passenger,<18
...,...,...,...,...,...,...,...,...,...,...,...,...
"Wynn, Mr. Walter",male,41.0,deck crew,B,England,NaN,NaN,1,NaN,deck crew,crew,30-45
"Yearsley, Mr. Harry",male,40.0,victualling crew,S,England,NaN,NaN,1,NaN,victualling crew,crew,30-45
"Young, Mr. Francis James",male,32.0,engineering crew,S,England,NaN,NaN,0,NaN,engineering crew,crew,30-45
"Zanetti, Sig. Minio",male,20.0,restaurant staff,S,England,NaN,NaN,0,NaN,restaurant staff,crew,18-30
"Zarracchi, Sig. L.",male,26.0,restaurant staff,S,England,NaN,NaN,0,NaN,restaurant staff,crew,18-30

Now we can treat the new variable as we would any other categorical variable.

In [42]:
df["age_categories"]

name
Abbing, Mr. Anthony               30-45
Abbott, Mr. Eugene Joseph           <18
Abbott, Mr. Rossmore Edward         <18
Abbott, Mrs. Rhoda Mary 'Rosa'    30-45
Abelseth, Miss. Karen Marie         <18
                                  ...
Wynn, Mr. Walter                  30-45
Yearsley, Mr. Harry               30-45
Young, Mr. Francis James          30-45
Zanetti, Sig. Minio               18-30
Zarracchi, Sig. L.                18-30
Name: age_categories, Length: 2207, dtype: category
Categories (5, object): ['<18' < '18-30' < '30-45' < '45-65' < '65+']

Arguments to the `cut` method can be specified to determine the treatment of the bin endpoints, but we won't go into the details here. There is also a `qcut` method which creates bins based on quantiles (e.g., the endpoints are the 25th, 50th, and 75th percentiles (along with the min and max).)

## Back to the Exercises about the Titanic data...

10\. Create a new country column that contains only the values United States, United Kingdom, or Other. (At the time of the Titanic, the countries in the United Kingdom were England, Scotland, Wales, and Ireland, including what is now Northern Ireland.) Don't overwrite the original country column.

In [43]:
def country_group(c):
    if c == "United States":
        return "United States"
    elif c in ["England", "Scotland", "Wales", "Ireland"]:
        return "United Kingdom"
    else:
        return "Other"

df["country_group"] = df["country"].map(country_group)

df[["country", "country_group"]]

                                      country   country_group
name
Abbing, Mr. Anthony             United States   United States
Abbott, Mr. Eugene Joseph       United States   United States
Abbott, Mr. Rossmore Edward     United States   United States
Abbott, Mrs. Rhoda Mary 'Rosa'        England  United Kingdom
Abelseth, Miss. Karen Marie            Norway           Other
...                                       ...             ...
Wynn, Mr. Walter                      England  United Kingdom
Yearsley, Mr. Harry                   England  United Kingdom
Young, Mr. Francis James              England  United Kingdom
Zanetti, Sig. Minio                   England  United Kingdom
Zarracchi, Sig. L.                    England  United Kingdom

[2207 rows x 2 columns]

11\. Create a new column that categorizes the fare variable into bins of length 5 from 0 to 25, bins of length 25 from 25 to 100, and 100+.

In [44]:
df["fare_category"] = pd.cut(
    df["fare"],
    bins=[0, 5, 10, 15, 20, 25, 50, 75, 100, float("inf")],
    labels=["0-5", "5-10", "10-15", "15-20", "20-25",
            "25-50", "50-75", "75-100", "100+"],
    include_lowest=True
)

df[["fare", "fare_category"]]

                                 fare fare_category
name
Abbing, Mr. Anthony              7.11          5-10
Abbott, Mr. Eugene Joseph       20.05         20-25
Abbott, Mr. Rossmore Edward     20.05         20-25
Abbott, Mrs. Rhoda Mary 'Rosa'  20.05         20-25
Abelseth, Miss. Karen Marie      7.13          5-10
...                               ...           ...
Wynn, Mr. Walter                  NaN           NaN
Yearsley, Mr. Harry               NaN           NaN
Young, Mr. Francis James          NaN           NaN
Zanetti, Sig. Minio               NaN           NaN
Zarracchi, Sig. L.                NaN           NaN

[2207 rows x 2 columns]

## Working with Gemini

Colab notebooks have [Gemini](), Google's AI, built in. Let's try it.

1\. Load either the Titanic data frame. After you load the data frame, there should be a button for "View recommended plot". Turn that button on and see what you get. Select one of the suggested plots that summarizes a single categorical variable. (Careful: make sure it's a single categorical variable. Some of the bar plots might be summarizing multiple variables.) What are features that you like about the plot? Are there any features you don't like?

2\. Now click on the "generate" with AI link, or the Gemini button. Write a prompt to reproduce some of your analysis from earlier in this notebook. You can copy and paste one of the questions, or you can try writing your own prompt. Run the code and examine the results. How successful was it?