---
title: "Practice Activity 4_1"
format:
  html:
    theme: cyborg
    embed-resources: true
---

# Practice Activity: Text Data - Spam Emails

In this activity you'll work with a small sample from the [Enron email corpus](https://en.wikipedia.org/wiki/Enron_Corpus). The [data set we'll use](https://raw.githubusercontent.com/kevindavisross/data301/refs/heads/main/data/enron_email.csv) contains the subjects and bodies of a sample of e-mails that the Federal Energy Regulatory Commission (FERC) collected during their 2002 investigation of the energy company [Enron](https://en.wikipedia.org/wiki/Enron). Each row in the data set is an email and there are three columns

- subject: the subject of the email
- body: the text of the email
- spam: spam indicator, 1 if spam, 0 if not

For this activity we will only consider the body of the emails (though you could also include the subject using similar methods).

1\. The corpus is the body column in the [data set](https://raw.githubusercontent.com/kevindavisross/data301/refs/heads/main/data/enron_email.csv); read this column in to create the corpus.

In [1]:
# ENTER YOUR CODE HERE. FEEL FREE TO ADD CELLS
import pandas as pd
import numpy as np

emails = pd.read_csv("https://raw.githubusercontent.com/kevindavisross/data301/refs/heads/main/data/enron_email.csv")
emails

,subject,body,spam
0,mirant 4 / 01,we invoiced mirant americas for deal 705989 an...,0.0
1,re : lobo payout,because the payback was done for october 2001 ...,0.0
2,entex transaction 7,"for december 1999 , since the volumes for tran...",0.0
3,re : hpl transport contracts,i would think that the first contract should g...,0.0
4,welcome to aol instant messenger !,welcome to the aol instant messenger ( sm ) se...,0.0
...,...,...,...
1985,customer reciept # 4359 bn winkle,simply visti our site and let ' s see if we ca...,NaN
1986,internet pharmacy - smart prices,order your medication here - no doctor visit n...,NaN
1987,victory at last,"wed , 09 jun 2004 13 : 33 : 18 - 0300\nsir or ...",NaN
1988,free pay per view,had chance at last to view the warner bros . l...,NaN
1989,87 % off for all new software . darned canniba...,"while example milk . water , own , make , wire...",NaN

In [2]:
corpus = emails["body"].fillna("")
corpus

0       we invoiced mirant americas for deal 705989 an...
1       because the payback was done for october 2001 ...
2       for december 1999 , since the volumes for tran...
3       i would think that the first contract should g...
4       welcome to the aol instant messenger ( sm ) se...
                              ...
1985    simply visti our site and let ' s see if we ca...
1986    order your medication here - no doctor visit n...
1987    wed , 09 jun 2004 13 : 33 : 18 - 0300\nsir or ...
1988    had chance at last to view the warner bros . l...
1989    while example milk . water , own , make , wire...
Name: body, Length: 1990, dtype: object

In [3]:
lowercorpus = corpus.str.lower()
lowercorpus[0]

'we invoiced mirant americas for deal 705989 and they do not see the deal in their system . it was for 5 , 000 / day from 4 / 1 - 4 / 2 at 5 . 10 on pg & e texas . can you tell me who you did this deal with at mirant ?\nmegan'

In [4]:
tokens = corpus.str.lower().str.findall(r"\w+")     # \w+ = a run of word characters
tokens[0]

['we',
 'invoiced',
 'mirant',
 'americas',
 'for',
 'deal',
 '705989',
 'and',
 'they',
 'do',
 'not',
 'see',
 'the',
 'deal',
 'in',
 'their',
 'system',
 'it',
 'was',
 'for',
 '5',
 '000',
 'day',
 'from',
 '4',
 '1',
 '4',
 '2',
 'at',
 '5',
 '10',
 'on',
 'pg',
 'e',
 'texas',
 'can',
 'you',
 'tell',
 'me',
 'who',
 'you',
 'did',
 'this',
 'deal',
 'with',
 'at',
 'mirant',
 'megan']

In [5]:
tokens.apply(len)

0        48
1       415
2        40
3       206
4       189
       ...
1985    162
1986     17
1987     99
1988    482
1989     68
Name: body, Length: 1990, dtype: int64

2\. Describe in words in detail the steps that you would take to clean the emails and create the term-frequency matrix. We will write the code in the next part, but think carefully first about the process: how do we turn this text into tabular data?

I would clean the email text by handling missing values, converting text to lowercase, and separating the text into words. Then I would use CountVectorizer to create a term-frequency matrix showing how often each word appears in each email.

3\. Use `CountVectorizer` to create the TF matrix, and then convert it to a pandas data frame with appropriate column names. You can just use the defaults in `CountVectorizer`. Hint: this should pretty much be a straight copy of code from the reading, but make sure you understand the process behind the code.

In [6]:
# ENTER YOUR CODE HERE. FEEL FREE TO ADD CELLS
from sklearn.feature_extraction.text import CountVectorizer

vec = CountVectorizer()
tf = vec.fit_transform(corpus)
tf_df = pd.DataFrame(tf.toarray(), columns=vec.get_feature_names_out())
tf_df

,00,000,0000,000000,000000000002858,000000000049773,000080,0001,00020608,0004,...,zyban,zykfe,zyl,zynsdirnh,zynve,zyqtaqlt,zyyqywp,zzezrjok,zzo,zzso
0,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1985,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1986,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1987,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1988,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1989,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

4\. Explain what a document frequency (DF) is, and the idea of an IDF. Why might we use TF-IDF rather than just TF? This question is asking about concepts rather than computations.

Document frequency is how many emails contain a word, while IDF gives more weight to words that appear in fewer emails. TF-IDF is useful because it reduces the importance of very common words and highlights words that better distinguish emails.

5\. Use `TfidfVectorizer` to create the TF matrix, and then convert it to a pandas data frame with appropriate column names. You can just use the defaults in `TfidfVectorizer`. Hint: this should pretty much be a straight copy of code from the reading, but make sure you understand the process behind the code.

In [7]:
# ENTER YOUR CODE HERE. FEEL FREE TO ADD CELLS

from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_vec = TfidfVectorizer()
tfidf = tfidf_vec.fit_transform(corpus)
tfidf_df = pd.DataFrame(tfidf.toarray(), columns=tfidf_vec.get_feature_names_out())
tfidf_df

,00,000,0000,000000,000000000002858,000000000049773,000080,0001,00020608,0004,...,zyban,zykfe,zyl,zynsdirnh,zynve,zyqtaqlt,zyyqywp,zzezrjok,zzo,zzso
0,0.0,0.106624,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0
1,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0
2,0.0,0.097060,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0
3,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0
4,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1985,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.11587,0.0
1986,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0
1987,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0
1988,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0
1989,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0

6\. Remember that the data set also contains an indicator of whether or not the email is spam. In this part you will use descriptive statistics and plots to compare the spam and non-spam emails in terms of their text, represented by the TF and TF-IDF matrices. This part is pretty open ended. First brainstorm some questions or things to investigate, and then write the code to produce relevant summaries.

Note: there are 10 emails for which the spam indicator is missing. You should remove them for this part. We'll come back to them soon.

In [8]:
# ENTER YOUR CODE HERE. FEEL FREE TO ADD CELLS
known = emails["spam"].notna()
spam = emails.loc[known, 'spam']

tf_known = tf_df[known]
tfidif_known = tfidf_df[known]
spam.value_counts()

spam
0.0    995
1.0    985
Name: count, dtype: int64

In [9]:
tf_known.sum(axis = 1).groupby(spam).describe().round(1)

      count   mean    std  min   25%   50%    75%     max
spam
0.0   995.0  135.3  181.6  0.0  28.0  74.0  174.5  1833.0
1.0   985.0  176.2  271.3  0.0  36.0  74.0  180.0  2594.0

7\. Now consider the 10 emails for which the true spam status is unknown. How might you decide if each email is spam or not? Brainstorm some ideas before proceeding. How can you use the TF and TF-IDF matrices for emails with known spam status?

I would compare each unknown email to emails with known spam labels using TF or TF-IDF similarity. If the closest emails are mostly spam, I would classify it as spam, and vice versa.

8\. Consider just one email with unknown spam status, with `loc` 1980. Compute the cosine distance between the TF representation of this email and the TF representation of each of the emails with known spam status.

In [10]:
# ENTER YOUR CODE HERE. FEEL FREE TO ADD CELLS
from sklearn.metrics.pairwise import cosine_distances

unknown_email = tf_df.loc[[1980]]
known_emails = tf_df[known]

distances = cosine_distances(unknown_email, known_emails)

distance_df = pd.DataFrame({
    "distance": distances[0],
    "spam": spam.values
}, index=known_emails.index)

distance_df

      distance  spam
0     0.736928   0.0
1     0.542990   0.0
2     0.775802   0.0
3     0.653954   0.0
4     0.519088   0.0
...        ...   ...
1975  0.944996   1.0
1976  0.649040   1.0
1977  0.448669   1.0
1978  0.693219   1.0
1979  0.931826   1.0

[1980 rows x 2 columns]

9\. Sort the results of the previous part to examine the emails with known spam status that are most similar to the unknown email. If you had to determine if the unknown email was spam or not, which would you pick and why?

In [11]:
# ENTER YOUR CODE HERE. FEEL FREE TO ADD CELLS
distance_df.sort_values("distance").head(10)

      distance  spam
1889  0.393060   1.0
1032  0.398488   1.0
1376  0.408606   1.0
714   0.414644   0.0
1110  0.415807   1.0
26    0.418573   0.0
180   0.423172   0.0
879   0.424620   0.0
713   0.427930   0.0
139   0.434841   0.0

I would classify email 1980 as spam because most of the emails with the smallest cosine distances are labeled as spam. Since smaller cosine distance means greater similarity, email 1980 appears to be more similar to spam emails.

10\. Repeat the two previous parts using TF-IDF instead of TF. Do the results change?

In [12]:
# ENTER YOUR CODE HERE. FEEL FREE TO ADD CELLS
unknown_email_tfidf = tfidf_df.loc[[1980]]
known_emails_tfidf = tfidf_df[known]

distances_tfidf = cosine_distances(
    unknown_email_tfidf,
    known_emails_tfidf
)

distance_tfidf_df = pd.DataFrame({
    "distance": distances_tfidf[0],
    "spam": spam.values
}, index=known_emails_tfidf.index)

distance_tfidf_df.sort_values("distance").head(10)

      distance  spam
1032  0.755245   1.0
1977  0.780917   1.0
48    0.787975   0.0
1689  0.790205   1.0
1796  0.795094   1.0
180   0.797415   0.0
586   0.798537   0.0
1376  0.799377   1.0
279   0.799969   0.0
1021  0.801259   1.0

Using TF-IDF, the 10 most similar emails are split evenly between spam and non-spam, so the result is inconclusive. This differs from the TF result, which leaned toward non-spam.

11\. Now proceed in a similar manner to "guess" the spam status of each of the unknown emails.

In [13]:
# ENTER YOUR CODE HERE. FEEL FREE TO ADD CELLS
unknown_indices = emails[emails["spam"].isna()].index

for idx in unknown_indices:
    unknown_email = tfidf_df.loc[[idx]]

    distances = cosine_distances(
        unknown_email,
        known_emails_tfidf
    )

    results = pd.DataFrame({
        "distance": distances[0],
        "spam": spam.values
    }, index=known_emails_tfidf.index)

    closest = results.sort_values("distance").head(10)

    print("Email:", idx)
    print(closest)
    print()

Email: 1980
      distance  spam
1032  0.755245   1.0
1977  0.780917   1.0
48    0.787975   0.0
1689  0.790205   1.0
1796  0.795094   1.0
180   0.797415   0.0
586   0.798537   0.0
1376  0.799377   1.0
279   0.799969   0.0
1021  0.801259   1.0

Email: 1981
     distance  spam
836  0.687836   0.0
428  0.701490   0.0
17   0.702135   0.0
564  0.709195   0.0
767  0.713070   0.0
422  0.714939   0.0
704  0.727138   0.0
46   0.729576   0.0
817  0.730769   0.0
210  0.735249   0.0

Email: 1982
      distance  spam
718   0.614962   0.0
1666  0.744678   1.0
751   0.792724   0.0
354   0.803658   0.0
744   0.810252   0.0
1038  0.815432   1.0
1725  0.817409   1.0
321   0.818855   0.0
374   0.821076   0.0
1611  0.838901   1.0

Email: 1983
     distance  spam
579  0.504036   0.0
270  0.531044   0.0
849  0.534733   0.0
25   0.539005   0.0
979  0.554830   0.0
185  0.558106   0.0
18   0.566685   0.0
226  0.568419   0.0
505  0.568443   0.0
450  0.570936   0.0

Email: 1984
     distance  spam
380  0.389829   0.0
749  0.423246   0.0
146  0.436402   0.0
214  0.467937   0.0
767  0.468155   0.0
20   0.483876   0.0
527  0.493100   0.0
191  0.545865   0.0
233  0.554096   0.0
75   0.567844   0.0

Email: 1985
      distance  spam
1028  0.371277   1.0
1633  0.719771   1.0
1412  0.768592   1.0
1893  0.776455   1.0
667   0.858551   0.0
842   0.862519   0.0
1958  0.864949   1.0
1372  0.864949   1.0
279   0.867408   0.0
1594  0.868196   1.0

Email: 1986
      distance  spam
1141  0.768513   1.0
1932  0.779266   1.0
1346  0.799405   1.0
1225  0.824340   1.0
1894  0.825025   1.0
1420  0.834116   1.0
1897  0.848996   1.0
1428  0.851043   1.0
1172  0.854928   1.0
1687  0.860522   1.0

Email: 1987
      distance  spam
1976  0.811616   1.0
1262  0.821986   1.0
1626  0.854460   1.0
1155  0.858995   1.0
1032  0.862875   1.0
1167  0.863727   1.0
1944  0.868144   1.0
1362  0.868947   1.0
124   0.873524   0.0
324   0.874729   0.0

Email: 1988
      distance  spam
1121  0.748163   1.0
1933  0.759515   1.0
1026  0.762197   1.0
1735  0.763446   1.0
1500  0.769080   1.0
1422  0.770276   1.0
1145  0.772414   1.0
1416  0.772903   1.0
1945  0.774616   1.0
1795  0.779405   1.0

Email: 1989
      distance  spam
245   0.856053   0.0
381   0.876010   0.0
961   0.895554   0.0
1413  0.901694   1.0
1779  0.902330   1.0
1114  0.907596   1.0
634   0.907793   0.0
1504  0.909428   1.0
228   0.912827   0.0
413   0.915870   0.0